[context.production]
  command = "make netlify"
  publish = "public"
  [context.production.environment]
    PYTHON_VERSION = "3.8"
    RUBY_VERSION = "2.7.2"

[context.development]
  command = "make netlify"
  publish = "public"
  [context.development.environment]
    PYTHON_VERSION = "3.8"
    RUBY_VERSION = "2.7.2"
