name: Disptach source-updated event
on:
  push:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -u  $REPO_ACCESS_TOKEN \
          -X POST \
          -H 'Accept: application/vnd.github.v3+json' \
          https://api.github.com/repos/redis-stack/redis-stack-website/dispatches \
          -d '{"event_type":"source-updated", "client_payload": $PAYLOAD}'
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          PAYLOAD: '{"github": ${{ toJson(github) }}}'
